packages:
  - apps/**/*
  - packages/**/*

overrides:
  "@payloadcms/db-postgres": "3.80.0"
  "@payloadcms/next": "3.80.0"
  "@payloadcms/plugin-nested-docs": "3.80.0"
  "@payloadcms/richtext-lexical": "3.80.0"
  "@payloadcms/translations": "3.80.0"
  "@payloadcms/ui": "3.80.0"
  "ajv": "^8.18.0"
  "devalue": "^5.6.4"
  "diff": "^8.0.3"
  "esbuild": "^0.25.0"
  "file-type": "^21.3.2"
  "h3": "^1.15.5"
  "lodash": "^4.17.23"
  "next": "16.2.0"
  "payload": "3.80.0"
  "react": "^19.2.3"
  "react-dom": "^19.2.3"
  "rollup": "^4.59.0"
  "smol-toml": "^1.6.1"
  "anymatch>picomatch": "^2.3.2"
  "astro>picomatch": "^4.0.4"
  "micromatch>picomatch": "^4.0.4"
  "readdirp>picomatch": "^2.3.2"
  "tinyglobby>picomatch": "^4.0.4"
  "vitest>picomatch": "^4.0.4"
  "svgo": "^4.0.1"
  "undici": "^7.18.2"
  "yaml": "^2.8.3"

allowBuilds:
  '@swc/core': true
  esbuild: true
  sharp: true

settings:
  minimumReleaseAge: 10080
