export const data = {
  root: {
    type: "root",
    format: "",
    indent: 0,
    version: 1,
    direction: "ltr",
    children: [
      // Heading
      {
        type: "heading",
        tag: "h1",
        format: "",
        indent: 0,
        version: 1,
        direction: "ltr",
        children: [
          {
            type: "text",
            text: "Welcome to the Astro RichText Renderer",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
        ],
      },
      // Paragraph with formatted text
      {
        type: "paragraph",
        format: "",
        indent: 0,
        version: 1,
        direction: "ltr",
        textFormat: 0,
        children: [
          {
            type: "text",
            text: "This is a ",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
          {
            type: "text",
            text: "bold",
            format: 1, // IS_BOLD
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
          {
            type: "text",
            text: " and ",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
          {
            type: "text",
            text: "italic",
            format: 2, // IS_ITALIC
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
          {
            type: "text",
            text: " text example. Here's some ",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
          {
            type: "text",
            text: "code",
            format: 16, // IS_CODE
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
          {
            type: "text",
            text: " inline.",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
        ],
      },
      // Heading 2
      {
        type: "heading",
        tag: "h2",
        format: "",
        indent: 0,
        version: 1,
        direction: "ltr",
        children: [
          {
            type: "text",
            text: "Text Formatting",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
        ],
      },
      // Paragraph with all text formats
      {
        type: "paragraph",
        format: "",
        indent: 0,
        version: 1,
        direction: "ltr",
        textFormat: 0,
        children: [
          {
            type: "text",
            text: "Strikethrough",
            format: 4, // IS_STRIKETHROUGH
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
          {
            type: "text",
            text: " | ",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
          {
            type: "text",
            text: "Underline",
            format: 8, // IS_UNDERLINE
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
          {
            type: "text",
            text: " | ",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
          {
            type: "text",
            text: "Subscript",
            format: 32, // IS_SUBSCRIPT
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
          {
            type: "text",
            text: " | ",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
          {
            type: "text",
            text: "Superscript",
            format: 64, // IS_SUPERSCRIPT
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
        ],
      },
      // Blockquote
      {
        type: "quote",
        format: "",
        indent: 0,
        version: 1,
        direction: "ltr",
        children: [
          {
            type: "text",
            text: "This is a blockquote. It can contain multiple lines of text and is useful for highlighting important quotes or citations.",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
        ],
      },
      // Heading 2
      {
        type: "heading",
        tag: "h2",
        format: "",
        indent: 0,
        version: 1,
        direction: "ltr",
        children: [
          {
            type: "text",
            text: "Lists",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
        ],
      },
      // Unordered list
      {
        type: "list",
        tag: "ul",
        listType: "bullet",
        format: "",
        indent: 0,
        version: 1,
        direction: "ltr",
        start: 1,
        children: [
          {
            type: "listitem",
            value: 1,
            format: "",
            indent: 0,
            version: 1,
            direction: "ltr",
            children: [
              {
                type: "text",
                text: "First bullet point",
                format: 0,
                mode: "normal",
                style: "",
                detail: 0,
                version: 1,
              },
            ],
          },
          {
            type: "listitem",
            value: 2,
            format: "",
            indent: 0,
            version: 1,
            direction: "ltr",
            children: [
              {
                type: "text",
                text: "Second bullet point",
                format: 0,
                mode: "normal",
                style: "",
                detail: 0,
                version: 1,
              },
            ],
          },
          {
            type: "listitem",
            value: 3,
            format: "",
            indent: 0,
            version: 1,
            direction: "ltr",
            children: [
              {
                type: "text",
                text: "Third bullet point with ",
                format: 0,
                mode: "normal",
                style: "",
                detail: 0,
                version: 1,
              },
              {
                type: "text",
                text: "bold text",
                format: 1,
                mode: "normal",
                style: "",
                detail: 0,
                version: 1,
              },
            ],
          },
        ],
      },
      // Ordered list
      {
        type: "list",
        tag: "ol",
        listType: "number",
        format: "",
        indent: 0,
        version: 1,
        direction: "ltr",
        start: 1,
        children: [
          {
            type: "listitem",
            value: 1,
            format: "",
            indent: 0,
            version: 1,
            direction: "ltr",
            children: [
              {
                type: "text",
                text: "First numbered item",
                format: 0,
                mode: "normal",
                style: "",
                detail: 0,
                version: 1,
              },
            ],
          },
          {
            type: "listitem",
            value: 2,
            format: "",
            indent: 0,
            version: 1,
            direction: "ltr",
            children: [
              {
                type: "text",
                text: "Second numbered item",
                format: 0,
                mode: "normal",
                style: "",
                detail: 0,
                version: 1,
              },
            ],
          },
        ],
      },
      // Heading 2
      {
        type: "heading",
        tag: "h2",
        format: "",
        indent: 0,
        version: 1,
        direction: "ltr",
        children: [
          {
            type: "text",
            text: "Links",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
        ],
      },
      // Paragraph with link
      {
        type: "paragraph",
        format: "",
        indent: 0,
        version: 1,
        direction: "ltr",
        textFormat: 0,
        children: [
          {
            type: "text",
            text: "Check out ",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
          {
            type: "link",
            format: "",
            indent: 0,
            version: 3,
            direction: "ltr",
            fields: {
              url: "https://payloadcms.com",
              newTab: true,
              linkType: "custom",
            },
            children: [
              {
                type: "text",
                text: "Payload CMS",
                format: 0,
                mode: "normal",
                style: "",
                detail: 0,
                version: 1,
              },
            ],
          },
          {
            type: "text",
            text: " for more information.",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
        ],
      },
      // Heading 2
      {
        type: "heading",
        tag: "h2",
        format: "",
        indent: 0,
        version: 1,
        direction: "ltr",
        children: [
          {
            type: "text",
            text: "Text Alignment",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
        ],
      },
      // Left aligned paragraph
      {
        type: "paragraph",
        format: "left",
        indent: 0,
        version: 1,
        direction: "ltr",
        textFormat: 0,
        children: [
          {
            type: "text",
            text: "This paragraph is left aligned.",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
        ],
      },
      // Center aligned paragraph
      {
        type: "paragraph",
        format: "center",
        indent: 0,
        version: 1,
        direction: "ltr",
        textFormat: 0,
        children: [
          {
            type: "text",
            text: "This paragraph is center aligned.",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
        ],
      },
      // Right aligned paragraph
      {
        type: "paragraph",
        format: "right",
        indent: 0,
        version: 1,
        direction: "ltr",
        textFormat: 0,
        children: [
          {
            type: "text",
            text: "This paragraph is right aligned.",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
        ],
      },
      // Indented paragraph
      {
        type: "paragraph",
        format: "",
        indent: 1,
        version: 1,
        direction: "ltr",
        textFormat: 0,
        children: [
          {
            type: "text",
            text: "This paragraph is indented (level 1).",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
        ],
      },
      // Custom Blocks Section
      {
        type: "heading",
        tag: "h2",
        format: "",
        indent: 0,
        version: 1,
        direction: "ltr",
        children: [
          {
            type: "text",
            text: "Custom Blocks",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
        ],
      },
      // Code Block
      {
        type: "block",
        format: "",
        indent: 0,
        version: 2,
        fields: {
          id: "code-block-1",
          blockType: "code",
          language: "typescript",
          code: "const greeting = (name: string): string => {\n  return `Hello, ${name}!`;\n};\n\nconsole.log(greeting('World'));",
        },
      },
      // Callout/Alert Block
      {
        type: "block",
        format: "",
        indent: 0,
        version: 2,
        fields: {
          id: "callout-1",
          blockType: "callout",
          type: "info",
          title: "Information",
          content: "This is an informational callout block. It can be used to highlight important information.",
        },
      },
      // Warning Callout
      {
        type: "block",
        format: "",
        indent: 0,
        version: 2,
        fields: {
          id: "callout-2",
          blockType: "callout",
          type: "warning",
          title: "Warning",
          content: "This is a warning callout. Use it to alert users about potential issues.",
        },
      },
      // Banner Block
      {
        type: "block",
        format: "",
        indent: 0,
        version: 2,
        fields: {
          id: "banner-1",
          blockType: "banner",
          style: "gradient",
          heading: "Featured Content",
          description: "This banner block demonstrates a more complex custom block with multiple fields.",
          buttonText: "Learn More",
          buttonUrl: "https://example.com",
        },
      },
      // Relationship/Reference Block
      {
        type: "block",
        format: "",
        indent: 0,
        version: 2,
        fields: {
          id: "relationship-1",
          blockType: "relationshipCard",
          relationTo: "posts",
          value: {
            id: "post-abc-123",
            title: "Introduction to Payload CMS",
            slug: "introduction-to-payload-cms",
            excerpt: "Learn how to build modern content management systems with Payload.",
            featuredImage: {
              url: "#",
              alt: "Payload CMS Dashboard",
            },
          },
        },
      },
      // Inline Blocks Section
      {
        type: "heading",
        tag: "h2",
        format: "",
        indent: 0,
        version: 1,
        direction: "ltr",
        children: [
          {
            type: "text",
            text: "Inline Blocks",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
        ],
      },
      // Paragraph with inline mention
      {
        type: "paragraph",
        format: "",
        indent: 0,
        version: 1,
        direction: "ltr",
        textFormat: 0,
        children: [
          {
            type: "text",
            text: "You can mention users like ",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
          {
            type: "inlineBlock",
            version: 2,
            fields: {
              id: "mention-1",
              blockType: "mention",
              userId: "user-123",
              username: "johndoe",
              displayName: "John Doe",
            },
          },
          {
            type: "text",
            text: " inline within your text content.",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
        ],
      },
      // Paragraph with inline badge/label
      {
        type: "paragraph",
        format: "",
        indent: 0,
        version: 1,
        direction: "ltr",
        textFormat: 0,
        children: [
          {
            type: "text",
            text: "Articles can have inline labels like ",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
          {
            type: "inlineBlock",
            version: 2,
            fields: {
              id: "label-1",
              blockType: "label",
              text: "New",
              color: "green",
            },
          },
          {
            type: "text",
            text: " or ",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
          {
            type: "inlineBlock",
            version: 2,
            fields: {
              id: "label-2",
              blockType: "label",
              text: "Featured",
              color: "blue",
            },
          },
          {
            type: "text",
            text: " to highlight content.",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
        ],
      },
      // Paragraph with inline math/equation
      {
        type: "paragraph",
        format: "",
        indent: 0,
        version: 1,
        direction: "ltr",
        textFormat: 0,
        children: [
          {
            type: "text",
            text: "Mathematical expressions can be rendered inline: ",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
          {
            type: "inlineBlock",
            version: 2,
            fields: {
              id: "math-1",
              blockType: "math",
              expression: "E = mc^2",
              displayMode: false,
            },
          },
          {
            type: "text",
            text: " is Einstein's famous equation.",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
        ],
      },
      // Table
      {
        type: "heading",
        tag: "h2",
        format: "",
        indent: 0,
        version: 1,
        direction: "ltr",
        children: [
          {
            type: "text",
            text: "Tables",
            format: 0,
            mode: "normal",
            style: "",
            detail: 0,
            version: 1,
          },
        ],
      },
      {
        type: "table",
        format: "",
        indent: 0,
        version: 1,
        direction: null,
        children: [
          {
            type: "tablerow",
            format: "",
            indent: 0,
            version: 1,
            direction: null,
            children: [
              {
                type: "tablecell",
                format: "",
                indent: 0,
                version: 1,
                direction: null,
                headerState: 1,
                colSpan: 1,
                rowSpan: 1,
                backgroundColor: null,
                children: [
                  {
                    type: "paragraph",
                    format: "",
                    indent: 0,
                    version: 1,
                    direction: "ltr",
                    textFormat: 0,
                    children: [
                      {
                        type: "text",
                        text: "Feature",
                        format: 1,
                        mode: "normal",
                        style: "",
                        detail: 0,
                        version: 1,
                      },
                    ],
                  },
                ],
              },
              {
                type: "tablecell",
                format: "",
                indent: 0,
                version: 1,
                direction: null,
                headerState: 1,
                colSpan: 1,
                rowSpan: 1,
                backgroundColor: null,
                children: [
                  {
                    type: "paragraph",
                    format: "",
                    indent: 0,
                    version: 1,
                    direction: "ltr",
                    textFormat: 0,
                    children: [
                      {
                        type: "text",
                        text: "Supported",
                        format: 1,
                        mode: "normal",
                        style: "",
                        detail: 0,
                        version: 1,
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            type: "tablerow",
            format: "",
            indent: 0,
            version: 1,
            direction: null,
            children: [
              {
                type: "tablecell",
                format: "",
                indent: 0,
                version: 1,
                direction: null,
                headerState: 0,
                colSpan: 1,
                rowSpan: 1,
                backgroundColor: null,
                children: [
                  {
                    type: "paragraph",
                    format: "",
                    indent: 0,
                    version: 1,
                    direction: "ltr",
                    textFormat: 0,
                    children: [
                      {
                        type: "text",
                        text: "Text formatting",
                        format: 0,
                        mode: "normal",
                        style: "",
                        detail: 0,
                        version: 1,
                      },
                    ],
                  },
                ],
              },
              {
                type: "tablecell",
                format: "",
                indent: 0,
                version: 1,
                direction: null,
                headerState: 0,
                colSpan: 1,
                rowSpan: 1,
                backgroundColor: null,
                children: [
                  {
                    type: "paragraph",
                    format: "",
                    indent: 0,
                    version: 1,
                    direction: "ltr",
                    textFormat: 0,
                    children: [
                      {
                        type: "text",
                        text: "Yes",
                        format: 0,
                        mode: "normal",
                        style: "",
                        detail: 0,
                        version: 1,
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            type: "tablerow",
            format: "",
            indent: 0,
            version: 1,
            direction: null,
            children: [
              {
                type: "tablecell",
                format: "",
                indent: 0,
                version: 1,
                direction: null,
                headerState: 0,
                colSpan: 1,
                rowSpan: 1,
                backgroundColor: null,
                children: [
                  {
                    type: "paragraph",
                    format: "",
                    indent: 0,
                    version: 1,
                    direction: "ltr",
                    textFormat: 0,
                    children: [
                      {
                        type: "text",
                        text: "Lists",
                        format: 0,
                        mode: "normal",
                        style: "",
                        detail: 0,
                        version: 1,
                      },
                    ],
                  },
                ],
              },
              {
                type: "tablecell",
                format: "",
                indent: 0,
                version: 1,
                direction: null,
                headerState: 0,
                colSpan: 1,
                rowSpan: 1,
                backgroundColor: null,
                children: [
                  {
                    type: "paragraph",
                    format: "",
                    indent: 0,
                    version: 1,
                    direction: "ltr",
                    textFormat: 0,
                    children: [
                      {
                        type: "text",
                        text: "Yes",
                        format: 0,
                        mode: "normal",
                        style: "",
                        detail: 0,
                        version: 1,
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            type: "tablerow",
            format: "",
            indent: 0,
            version: 1,
            direction: null,
            children: [
              {
                type: "tablecell",
                format: "",
                indent: 0,
                version: 1,
                direction: null,
                headerState: 0,
                colSpan: 1,
                rowSpan: 1,
                backgroundColor: null,
                children: [
                  {
                    type: "paragraph",
                    format: "",
                    indent: 0,
                    version: 1,
                    direction: "ltr",
                    textFormat: 0,
                    children: [
                      {
                        type: "text",
                        text: "Tables",
                        format: 0,
                        mode: "normal",
                        style: "",
                        detail: 0,
                        version: 1,
                      },
                    ],
                  },
                ],
              },
              {
                type: "tablecell",
                format: "",
                indent: 0,
                version: 1,
                direction: null,
                headerState: 0,
                colSpan: 1,
                rowSpan: 1,
                backgroundColor: null,
                children: [
                  {
                    type: "paragraph",
                    format: "",
                    indent: 0,
                    version: 1,
                    direction: "ltr",
                    textFormat: 0,
                    children: [
                      {
                        type: "text",
                        text: "Yes",
                        format: 0,
                        mode: "normal",
                        style: "",
                        detail: 0,
                        version: 1,
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
};
